# -----------------------
# Builder Stage
# -----------------------
FROM node:22-alpine AS builder

# Installer les dépendances système nécessaires pour Prisma
RUN apk add --no-cache bash curl openssl libc6-compat

WORKDIR /app

# Copier uniquement package.json / package-lock.json pour le cache Docker
COPY package*.json ./

# Installer les dépendances
RUN npm ci

# Copier le reste du code
COPY . .

# Générer le client Prisma
RUN npx prisma generate

# Builder Next.js
RUN npm run build

# -----------------------
# Production Stage
# -----------------------
FROM node:22-alpine AS prod

WORKDIR /app

# Définir l'environnement
ENV NODE_ENV=production

# Installer les dépendances système nécessaires pour Prisma
RUN apk add --no-cache bash openssl libc6-compat

# Copier node_modules et le code depuis le builder
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/ ./

# Exposer le port de l'app
EXPOSE 4004

# Commande pour lancer l'app
CMD ["npm", "start"]