services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: lumilaya
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
    dns:
      - 8.8.8.8
      - 1.1.1.1
    dns_search: ""
    networks:
      - prod-network
      - nginx-network
      - mongo-network
      - redis-network
    ports:
      - "4004:4004"  # expose uniquement le port de ton app

# Réseaux externes existants
networks:
  nginx-network:
    external: true
  mongo-network:
    external: true
  redis-network:
    external: true

  # Réseau interne pour le container web avec sortie Internet
  prod-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      config:
        - subnet: 172.25.0.0/16